supermakte/supermakte/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='user')),
]

supermakte/user/urls.py
from django.conf.urls import url

from user.views import reg, login, infor, member, address

urlpatterns = [
    url(r'^reg/$', reg, name='注册'),
    url(r'^login/$', login, name='登录'),
    url(r'^infor/$', infor, name='个人资料'),
    url(r'^member/$', member, name='个人中心'),
    url(r'^address/$', address, name='收货地址'),

]

supermakte/user/models.py
from django.db import models

# Create your models here.

supermakte/user/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.

# 注册
def reg(request):
    if request.method == 'POST':
        mobile = request.POST.get('mobile')
        repassword = request.POST.get('repassword')
        password = request.POST.get('password')

    return render(request, 'user/reg.html')


# 登录

def login(request):
    return render(request, 'user/login.html')


# 个人资料

def infor(request):
    return render(request, 'user/infor.html')


# 个人中心

def member(request):
    return render(request, 'user/member.html')


# 收货地址

def address(request):
    return render(request, 'user/address.html')

supermakte/templates/include/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>超市</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <link rel="icon" type="image/png" href="/theme/default/images/favicon.png">
    <link href="{% static 'css/amazeui.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'js/time.js' %}"></script>
    <script src="{% static 'js/popup.mini.js' %}"></script>
    <link href="{% static 'css/check.css' %}" rel="stylesheet" type="text/css" />
    <script src="{% static 'js/area.js' %}"></script>
</head>
<body>

        {% block herder %}

        {% endblock %}


        {% block content %}

        {% endblock %}

        {% block footer %}


        {% endblock %}

        {% block footr_css %}
        {% endblock %}

        {% block footr_js %}
             <script src="{% static 'js/jquery.min.js' %}"></script>
             <script src="{% static 'js/amazeui.min.js' %}"></script>
        {% endblock %}

    </body>
</html>

supermakte/templates/user/address.html
{% extends 'include/base.html' %}
{% load static %}

	<body>
    {% block herder %}
        <header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">新增收货地址</a>
            </h1>
	    </header>

    {% endblock %}

    {% block content %}
          <div style="height: 60px;"></div>
	    <ul class="address">
	    	<li>
	    		<a href="village.html"><input type="text" class="add-input"  disabled="disabled" placeholder="宿舍区" />
	    		<i class="am-icon-angle-right" style="float: right; margin-top: 5px;"></i></a>
	    	</li>
	    	<li>
	    		<a href="village.html"><input type="text" class="add-input"  disabled="disabled" placeholder="哪栋楼" />
	    		<i class="am-icon-angle-right" style="float: right; margin-top: 5px;"></i></a>
	    	</li>
	    	<li><input type="text" class="add-input" placeholder="你在哪" /></li>
	    	<li><input type="text" class="add-input" placeholder="收货人" /></li>
	    	<li><input type="text" class="add-input" placeholder="13000000000" /></li>
	    </ul>
	    <div class="moren">
	    	<label class="am-checkbox am-warning">
                 <input type="checkbox" checked="checked" value="" data-am-ucheck checked>设为默认
            </label>

	    </div>
	    <input type="button" class="login-btn" value="确认提交">

    {% endblock %}


	</body>

supermakte/templates/user/infor.html
{% extends 'include/base.html' %}
{% load static %}
	<body>
		{% block herder %}
            <header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">个人资料</a>
            </h1>
	    </header>

		{% endblock %}
	   {% block content %}
            <div style="height: 49px;"></div>
	    <ul class="safty1">
	    	<li>
	    		<a href="">
	    			<i style="margin-top: 25px;">头像</i>
	    			<div class="infor-pic">
	    				<img src="{% static 'images/infortx.png' %}" />
	    			</div>
	    		</a>
	    	</li>
	    	<li>
	    		<a href="">
	    			<i>昵称</i>
	    			<input class="infor-tele" placeholder="默契"/>
	    		</a>
	    	</li>
	    	<li>
	    		<a href="">
	    			<i>性别</i>
	    			<i class="infor-tele">
	    				<label class="am-radio-inline">
				          <input type="radio" name="radio10" checked="checked" value="1" data-am-ucheck>男
				        </label>
				        <label class="am-radio-inline">
				          <input type="radio" name="radio10" value="1" data-am-ucheck>女
				        </label>
	    			</i>
	    		</a>
	    	</li><li>
	    		<a href="">
	    			<i>生日</i>
                    <input class="infor-tele" placeholder="出生日期"/>
	    		</a>
	    	</li>
	    </ul>
	    <div style="height: 10px; background: #efefef;"></div>
	     <ul class="safty1">
	    	<li>
	    			<i>学校</i>
	    			<input class="infor-tele" placeholder="就读于哪个学校"/>
	    	</li>
	    	<li>
	    			<i>位置</i>
	    			<input class="infor-tele" placeholder="详细地址"/>
	    	</li>
	    	<li>
	    			<i>故乡</i>
                    <input class="infor-tele" placeholder="来自哪里"/>
	    	</li>
	    	<li>
	    			<i>手机</i>
                    <input class="infor-tele" placeholder="13012345678"/>
	    	</li>
	    </ul>

	   {% endblock %}

	</body>
</html>

supermakte/templates/user/login.html
{% extends 'include/base.html' %}
{% load static %}
{% block herder %}
<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">登录</a>
            </h1>
	    </header>


{% endblock %}
{% block content %}


	<body>

	    <div style="height: 49px;"></div>

	    <div style="height: 3rem;"></div>
	    <input type="text" name="mobile" id="mobile" placeholder="请输入用户名/手机号" class="login-name">
	    <input type="password" name="password" id="password" placeholder="请输入密码" class="login-password">
	    <input type="button" class="login-btn" value="我要登录">
	    <div class="agree">
	    	<a href="{% url 'user:注册' %}">免费注册</a>
	    	<a href="forgetpassword.html" class="forget">忘记密码？</a>
	    </div>
	    <div class="line"></div>
	    <div class="line-text">第三方账号登录</div>
	    <ul class="second-login">
	    	<li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
	    	<li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
	    	<li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
	    </ul>
    </body>
{% endblock %}

supermakte/templates/user/member.html
{% extends 'include/base.html' %}
{% load static %}
	<body style="background: #f6f6f6;">
    {% block herder %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
			<h1 class="am-header-title">
  	            <a href="" class="">个人中心</a>
            </h1>
	    </header>
    {% endblock %}
    {% block content %}
           <div style="height: 49px;"></div>
	    <div class="member">
	    	<div class="mem-tit">15078921546
	    		<a href="step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
	    	</div>
	    	<div class="mem-pic">
		    	<div class="mem-pic-bg" style="background-image: url(images/memtx.png);"></div>
	    	</div>
	    	<ul class="member-menu">
			<li>
				<a href="records.html">
					<p class="yellow">0</p>
					<p class="black">帐户余额 </p>
				</a>
			</li>
            <li>
				<a href="integral.html">
					<p class="yellow">0</p>
					<p class="black">积分 </p>
				</a>
			</li>
			<li>
				<a href="yhq.html">
					<p class="yellow">0</p>
					<p class="black">优惠劵 </p>
				</a>
			</li>
			<li>
				<a href="collect.html">
					<p class="yellow">0</p>
					<p class="black">我的收藏 </p>
				</a>
			</li>
		</ul>
	    </div>
	    <div class="user-list">
		  	<div class="u-list-main">
		  		<img src="{% static 'images/order-pic.png' %}" width="27" />
		  		<span>我的购物订单</span>
		  		<a href="allorder.html">查看全部订单></a>
		  	</div>
		    <ul class="user-nav">
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon.png' %}"> <p>待付款</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon1.png' %}"> <p>待收货</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon2.png' %}"> <p>待评价</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon3.png' %}"> <p>退换货</p></a></li>
		    </ul>
		    <div class="u-list-main">
		  		<img src="{% static 'images/order-my.png' %}" width="27" />
		  		<span>帐户与安全</span>
		  	</div>
		    <ul class="user-nav">
		    	<li><a href="{% url 'user:个人资料' %}"> <img src="{% static 'images/1-icon4.png' %}"> <p>个人资料</p></a></li>
		    	<li><a href="gladdress.html"> <img src="{% static 'images/1-icon5.png' %}"> <p>收货地址</p></a></li>
		    	<li><a href="saftystep.html"> <img src="{% static 'images/1-icon6.png' %}"> <p>安全设置</p></a></li>
		    	<li><a href="money.html"> <img src="{% static 'images/1-icon7.png' %}"> <p>我的钱包</p></a></li>
		    </ul>
	    </div>
	    <!--导航-->
 <ul class="sq-nav" style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
      <li>
        <div class="am-gallery-item">
            <a href="job.html" class="">
              <img src="{% static 'images/m_03.png' %}" />
              <p>我要兼职</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="recommend.html" class="">
              <img src="{% static 'images/m_04.png' %}" />
              <p>推荐有奖</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="myrecommend.html" class="">
              <img src="{% static 'images/m_05.png' %}" />
              <p>我的推荐</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/m_06.png' %}" />
              <p>我的佣金</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="yhq.html" class="">
              <img src="{% static 'images/m_02.png' %}" />
              <p>我的红包</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="message.html" class="">
              <img src="{% static 'images/m_07.png' %}" />
              <p>我的动态</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="javascript:;" class="index-qd">
              <img src="{% static 'images/m_08.png' %}" />
              <p>客服中心</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/m_09.png' %}" />
              <p>安全退出</p>
            </a>
        </div>
      </li>
      </ul>
      </div>
    <!--客服中心-->
<div class="qd-box">
	<div class="popup-title">
			<span>客服中心</span>
			<div class="popup-close"><i class="iconfont">&#xe602</i></div>
	</div>
	<div class="dq-text">
		<a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
			<img src="{% static 'images/contactqq.png' %}" width="50" />
			<p class="contactqq">联系QQ</p>
		</a>
		<a href="tel:0791-12345678">
			<img src="{% static 'images/contacttele.png' %}"  width="50" />
			<p class="contacttele">呼叫电话</p>
		</a>
	</div>
</div>

    {% endblock %}

    {% block footer %}
        <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">
          <li>
            <a href="index.html" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="shopcart.html" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="allorder.html" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>

          <li>
            <a href="member.html" class="curr">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>


    {% endblock %}




<!--客服中心-->
      <!--底部-->




 <script type='text/javascript'>
	(function(){
		 new PopUp_api({el:'.index-qd',html:'.qd-box'});
	})()
</script>


	</body>
</html>

supermakte/templates/user/reg.html
{% extends 'include/base.html' %}
{% load static %}

	<body>
    {% block herder %}
        	<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">注册</a>
            </h1>
	    </header>

    {% endblock %}

    {% block content %}
        <div style="height: 49px;"></div>
	    <!--<div class="login-logo">
	    	<img src="images/logo.png" />
	    </div>-->
	    <div style="height: 3rem;"></div>
        <form action="" method="post">
         <input type="text" name="mobile"  placeholder="请输入手机号" class="login-name">
	    <input type="text" name="repassword"  placeholder="请输入密码" class="login-password">
	    <input type="password" name="password"  placeholder="确认密码" class="login-name">
	    <div class="yzm" style="margin-top: 1.5rem;">
	    	<input type="text" class="reg-yzm" placeholder="输入验证码" />
	    	<input type="button" class="yzm-hq" value="获取验证码" />
            <input type="submit" class="login-btn" value="立即注册">
            </div>
        </form>



	    <div class="agree">
	    	<input type="checkbox" name="checkbox" value="同意" checked="">&nbsp;同意
		    <a href="" class="xy">《用户协议》</a>
		      <div class="r-login">已有账号，请<a href="{% url 'user:登录' %}" class="l-login">登录</a></div>
	    </div>

    {% endblock %}


	   
	</body>
</html>